### PR TITLE
Fixes issue #75

### PR DESCRIPTION
**Pull request by EliAgne**
Copied dimension classes over since they are only used for holding the width and height.

Replaced the ImageUtils class for spreadsheets and reads the file contents to determine size versus using javax.imageio classes.

### CODE REVIEW

**Comment by centic9** [comment]
Thanks for the work! 

* Is ImageUtils duplicated here from Apache POI? Does it need changes? This would make the code fairly brittle as every change in Apache POI itself could then cause very hard to find issues.
* Are the two image-files needed? If you would like to add a "test-button" in the sample-app to show that picture-resizing works now, then this can be implemented in https://github.com/centic9/poi-on-android/blob/master/poitest/src/main/java/org/dstadler/poiandroidtest/poitest/MainActivity.java

**Comment by EliAgne** [comment]
Thanks for heading the port to android. Yeah everything was the same from ImageUtils except I changed the getImageDimension method to not make any calls to the javax.imageio classes. I thought it would be a safe-enough change considering that getImageDimension seems to only be called in ImageUtils. But yeah that's a good point, it could cause some unforeseen issues.

Yeah it looks like there would need to be some abstraction of the Apache POI's image I/O to allow other JVM systems (that don't have javax) to register their own Image I/O provider. Then a system could implement the abstract methods and register it as the provider, or something like that. But abstracting that, then reimplementing that with android's graphics seems like a lot of work and I'm not sure how feasible it would be. That might be a difficult merge request to get through. 

Good idea, I'll look to add the scenarios for the other supported file formats.

**Comment by centic9** [comment]
Is there a way to provide the replacement-code via classes in the javax.imageio package and relocate it similar to the awt classes so that Apache POI can stay unchanged?

**Comment by EliAgne** [comment]
I added only necessary shadow classes for java.awt and java.imageio and added some compatibility classes for reading image files. The functionality is only focused on fixing the resizing issue, but would still have some functionality in other areas that uses those same methods. Or at least maybe a good starting point if other compatibility is desired.

**Comment by centic9** [comment]
Thanks for the work, I'll try to take a look in the coming days.

**Comment by centic9** [comment]
Thanks a lot for the changed approach, works great when testing the sample-app!

**Pull request merged**
